import { motion } from "framer-motion";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const Portfolio = () => {
  return (
    <div className="min-h-screen bg-black text-foreground">
      <Navigation />
      
      {/* Hero Section */}
      <motion.section 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        className="relative container px-4 pt-40 pb-20"
      >
        <div className="max-w-4xl mx-auto text-center relative z-10">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.8 }}
            className="text-6xl md:text-7xl font-normal mb-6 tracking-tight"
          >
            Portfolio
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4, duration: 0.8 }}
            className="text-lg md:text-xl text-muted-foreground mb-8 max-w-xl mx-auto"
          >
            View our ready to post content generated by AI.
          </motion.p>
        </div>
      </motion.section>

      {/* Original Image Section */}
      <motion.section 
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8 }}
        className="py-24"
      >
        <div className="px-4 max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1, duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-normal mb-6 tracking-tight">
              <span className="text-gradient font-medium">Original Images</span>
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Starting point provided by the client
            </p>
          </motion.div>
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2, duration: 0.8 }}
            className="grid grid-cols-1 lg:grid-cols-3 gap-6 max-w-6xl mx-auto"
          >
            <div className="glass rounded-xl overflow-hidden w-full relative aspect-[4/5]">
              <img
                src="/lovable-uploads/Original1.jpg"
                alt="Original Image 1"
                className="w-full h-full object-cover relative z-10"
                loading="lazy"
              />
            </div>
            <div className="glass rounded-xl overflow-hidden w-full relative aspect-[4/5]">
              <img
                src="/lovable-uploads/Original2.jpg"
                alt="Original Image 2"
                className="w-full h-full object-cover relative z-10"
                loading="lazy"
              />
            </div>
            <div className="glass rounded-xl overflow-hidden w-full relative aspect-[4/5]">
              <img
                src="/lovable-uploads/Original3.jpg"
                alt="Original Image 3"
                className="w-full h-full object-cover relative z-10"
                loading="lazy"
              />
            </div>
          </motion.div>
        </div>
      </motion.section>

      {/* AI Generated Content Section (matches landing page) */}
      <section className="py-24">
        <div className="px-4 max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-normal mb-6 tracking-tight">
              <span className="text-gradient font-medium">AI Generated Content</span>
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Professional variations created by our AI system
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
            {["1.png","2.png","3.png","4.png","5.png","6.png","7.png","8.png","9.png","10.png"].map((filename, idx) => (
              <div
                key={filename}
                className="glass rounded-xl overflow-hidden w-full relative aspect-[4/5]"
              >
                <img
                  src={`/lovable-uploads/${filename}`}
                  alt={`AI Generated Content ${filename}`}
                  className="w-full h-full object-cover relative z-10"
                  loading="lazy"
                />
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default Portfolio;